### ISSUE TITLE
ModuleNotFoundError: No module named 'cpuinfo' while running pip install -r requirements.txt MacOS Sequoia 15.1.1 (intel, AMD)

### ISSUE THREAD

**Issue by SkyForceCoder** [BoBo0037/bobo-fun#3]
----

> **Processor:**

Model: Intel(R) Xeon(R) W-2140B CPU
Speed: 3.20 GHz
Cores: 8 cores (with Hyper-Threading enabled)

> **Memory (RAM):**

Total RAM: 32 GB (34359738368 bytes)

> **GPU:**

Model: Radeon Pro Vega 56
VRAM: 8 GB
Bus: PCIe (x16)
Metal Support: Metal 3 (supports Apple's graphics framework)

Step to reproduce

conda create --name bobo python=3.11
conda activate bobo

Here i get error:https://github.com/BoBo0037/bobo-fun/issues/2
conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 -c pytorch

So I used it
conda install pytorch torchvision torchaudio -c pytorch

% cd bobo-fun
% pip install requirements.txt

----

Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/setup.py", line 41, in <module>
          from op_builder.all_ops import ALL_OPS, accelerator_name
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/op_builder/all_ops.py", line 29, in <module>
          builder = get_accelerator().create_op_builder(member_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/accelerator/mps_accelerator.py", line 244, in create_op_builder
          builder_class = self.get_op_builder(op_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/accelerator/mps_accelerator.py", line 251, in get_op_builder
          from deepspeed.ops.op_builder.cpu import NotImplementedBuilder
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/__init__.py", line 25, in <module>
          from . import ops
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/ops/__init__.py", line 6, in <module>
          from . import adam
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/ops/adam/__init__.py", line 6, in <module>
          from .cpu_adam import DeepSpeedCPUAdam
        File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/ops/adam/cpu_adam.py", line 7, in <module>
          from cpuinfo import get_cpu_info
      ModuleNotFoundError: No module named 'cpuinfo'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

----

I installed this one and its working
https://pypi.org/project/py-cpuinfo/
pip install py-cpuinfo

**Comment by BoBo0037** [comment]
> > **Processor:**
> 
> Model: Intel(R) Xeon(R) W-2140B CPU Speed: 3.20 GHz Cores: 8 cores (with Hyper-Threading enabled)
> 
> > **Memory (RAM):**
> 
> Total RAM: 32 GB (34359738368 bytes)
> 
> > **GPU:**
> 
> Model: Radeon Pro Vega 56 VRAM: 8 GB Bus: PCIe (x16) Metal Support: Metal 3 (supports Apple's graphics framework)
> 
> Step to reproduce
> 
> conda create --name bobo python=3.11 conda activate bobo
> 
> Here i get error:#2 conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 -c pytorch
> 
> So I used it conda install pytorch torchvision torchaudio -c pytorch
> 
> % cd bobo-fun % pip install requirements.txt
> 
> Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/setup.py", line 41, in from op_builder.all_ops import ALL_OPS, accelerator_name File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/op_builder/all_ops.py", line 29, in builder = get_accelerator().create_op_builder(member_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/accelerator/mps_accelerator.py", line 244, in create_op_builder builder_class = self.get_op_builder(op_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/accelerator/mps_accelerator.py", line 251, in get_op_builder from deepspeed.ops.op_builder.cpu import NotImplementedBuilder File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/**init**.py", line 25, in from . import ops File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/ops/**init**.py", line 6, in from . import adam File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/ops/adam/**init**.py", line 6, in from .cpu_adam import DeepSpeedCPUAdam File "/private/var/folders/w0/xlqps1cd7sd504jwq_1rr5y00000gn/T/pip-install-snh63lnp/deepspeed_e0c8fbec6e024596bb83d6c53a96da82/deepspeed/ops/adam/cpu_adam.py", line 7, in from cpuinfo import get_cpu_info ModuleNotFoundError: No module named 'cpuinfo' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> I installed this one and its working https://pypi.org/project/py-cpuinfo/ pip install py-cpuinfo

yes, right.  **pip install py-cpuinfo==9.0.0**  is ok
